version: '3'
services:

  #PHP Service
  app-private:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-private
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app-private
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker-config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - $HOME/.ssh:/home/www/.ssh
    networks:
      - default

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db-private
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker-config/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - default
#Volumes
networks:
  default:
    name: gluu_default
    external: true
volumes:
  dbdata:
    driver: local


